package view.component;

import javax.swing.*;
import java.awt.*;

public class BusyDialog extends JDialog {
    private JPanel contentPane;
    private JProgressBar progressBar;
    private JLabel msgLbl;


    public BusyDialog(String msg) {
        setContentPane(contentPane);
        setModal(true);
        this.setLocationRelativeTo(null);
        this.msgLbl.setText(msg);
        this.progressBar.setIndeterminate(true);
        this.setUndecorated(true);
        this.pack();
        this.setResizable(false);

    }

    public void setMaxProgress(int max) {
        this.progressBar.setMaximum(max);
    }

    public void setProgress(int value) {
        if (this.progressBar.isIndeterminate()) {
            this.progressBar.setIndeterminate(false);
        }
        this.progressBar.setValue(value);
    }

    public static void main(String[] args) {

        BusyDialog dialog = new BusyDialog("Setting new cofiguration...");

        dialog.setVisible(true);
        System.exit(0);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        msgLbl = new JLabel();
        msgLbl.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        contentPane.add(msgLbl, gbc);
        progressBar = new JProgressBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 10, 5, 10);
        contentPane.add(progressBar, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
