package view.component.trainingview;

import javax.swing.*;
import java.awt.*;
import java.util.Map;
import java.util.List;

public class TrainingReportDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JPanel learnerProfilePanel;
    private JLabel cvaScoreLbl;
    private JLabel testScoreLbl;
    private JLabel trainingSizeLbl;
    private JLabel featureSelectionLbl;
    private JLabel testingSizeLbl;

    private TrainingReportDialog(Map<String, Object> report) {
        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
        setTitle("Training Report");
        buttonOK.addActionListener(e -> onOK());

        this.fillReport(report);
        this.pack();
        this.setResizable(false);
    }

    private void fillReport(Map<String, Object> report) {
        this.cvaScoreLbl.setText(String.format("%.2f%%(+/-%.2f%%, %d folds)", ((Double) report.get("cv_score_mean")) * 100, ((Double) report.get("cv_score_std")) * 100, report.get("cv_folds")));
        this.testScoreLbl.setText(String.format("%.2f%%", ((Double) report.get("test_score")) * 100));
        this.featureSelectionLbl.setText(report.get("feature_selections").toString());
        this.trainingSizeLbl.setText(report.get("training_size").toString());
        this.testingSizeLbl.setText(report.get("testing_size").toString());
        this.fillLearnerInfo((List<Object[]>) report.get("learner_info"));

    }

    private void fillLearnerInfo(List<Object[]> learnerInfo) {
        Box rowBox;

        for (Object[] row : learnerInfo) {
            rowBox = Box.createHorizontalBox();
            rowBox.add(new JLabel(row[0].toString() + ":"));
            rowBox.add(Box.createHorizontalStrut(10));
            rowBox.add(new JLabel(row[1].toString()));
            rowBox.add(Box.createHorizontalGlue());
            this.learnerProfilePanel.add(rowBox);
        }
    }

    private void onOK() {
        dispose();
    }

    public static void showReport(Map report) {
        TrainingReportDialog dialog = new TrainingReportDialog(report);
        dialog.setVisible(true);
    }

    private void createUIComponents() {
        learnerProfilePanel = new JPanel();
        learnerProfilePanel.setLayout(new BoxLayout(learnerProfilePanel, BoxLayout.Y_AXIS));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel1, gbc);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(buttonOK, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel2, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, label1.getFont().getSize()));
        label1.setText("Cross Validation Average Score");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        panel2.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, label2.getFont().getSize()));
        label2.setText("Test Score");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        panel2.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, label3.getFont().getSize()));
        label3.setText("Size of Training Dataset");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        panel2.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setFont(new Font(label4.getFont().getName(), Font.BOLD, label4.getFont().getSize()));
        label4.setText("Classifier");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        panel2.add(label4, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(learnerProfilePanel, gbc);
        testScoreLbl = new JLabel();
        testScoreLbl.setText("0%");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(testScoreLbl, gbc);
        trainingSizeLbl = new JLabel();
        trainingSizeLbl.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(trainingSizeLbl, gbc);
        cvaScoreLbl = new JLabel();
        cvaScoreLbl.setText("0%");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(cvaScoreLbl, gbc);
        final JLabel label5 = new JLabel();
        label5.setFont(new Font(label5.getFont().getName(), Font.BOLD, label5.getFont().getSize()));
        label5.setText("Feature Selection");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label5, gbc);
        featureSelectionLbl = new JLabel();
        featureSelectionLbl.setText("None");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(featureSelectionLbl, gbc);
        final JLabel label6 = new JLabel();
        label6.setFont(new Font(label6.getFont().getName(), Font.BOLD, label6.getFont().getSize()));
        label6.setText("Size of Testing Dataset");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        panel2.add(label6, gbc);
        testingSizeLbl = new JLabel();
        testingSizeLbl.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(testingSizeLbl, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */


}
